global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_protocols:
    - OpenMetricsText1.0.0
    - OpenMetricsText0.0.1
    - PrometheusProto
    - PrometheusText0.0.4

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["localhost:8889"]

  - job_name: "api-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:7070"]

  - job_name: "authentication-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9001"]

  - job_name: "application-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9004"]


  - job_name: "access-management-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9000"]

  
  - job_name: "uno-job-scheduler-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:3001"]